# -*- coding: utf-8 -*-
"""finca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAd1MSQMMPRsezweE8EAvwMJdbaQE8Ez
"""

#Finca raiz nuevo diseño MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-sm-6 MuiGrid-grid-lg-4 MuiGrid-grid-xl-4
import pandas as pd
import re
import requests
import numpy as np
from bs4 import BeautifulSoup
from datetime import datetime 
from selenium import webdriver
from selenium.common.exceptions import WebDriverException as WDE #Manejo de exepciones
from selenium.webdriver.chrome.options import Options
import time
date=datetime.now() #Trae la fecha
fecha=date.strftime("%Y-%m-%d %H-%M-%S")#Arma la fecha en el formato Año Mes día horas minutos y segundos
fecha_busqueda = date.strftime("%Y-%m-%d")
ano=date.strftime("%Y")#toma el año de la consulta
mes=date.strftime("%m")#toma el mes de la consulta
dia=date.strftime("%d") #toma el día de la consulta
data=[] #Lista donde se almacenan los diferentes valores que devuelve el scraping
urls = []
registros = 0
for i in range(1,2):    
    options=webdriver.ChromeOptions() 
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    driver=webdriver.Chrome(options=options)
    #https://www.fincaraiz.com.co/apartamentos/venta/medellin?pagina=
    url_finca = "https://fincaraiz.com.co/apartamentos/venta?ubicacion=Medell%C3%ADn%2C+Antioquia%2C+Calazans&pagina="+str(i)
    print(url_finca)
    try:
        driver.get(url_finca)
        elem = driver.find_element_by_xpath("//*")
        source_code = elem.get_attribute("innerHTML")
        page=str(source_code)
        finca_raiz = BeautifulSoup(page,'html.parser')
        url_modificada = ''
        url_recibida = str(finca_raiz)
        url_modificada = re.findall(r'MuiTypography-root MuiLink-root MuiLink-underlineHover jss\d+\sjss\d+\sMuiTypography-colorPrimary',url_recibida)[0]
    except: 
        print("Un error ha ocurrido")
    for val in finca_raiz.find_all('a',attrs={'class':url_modificada}):
        urls.append('https://www.fincaraiz.com.co'+val['href'])
    
    try:
        driver.close()
    except:
        print("Problema para cerrar")
#Código para armar los ítems
for dire in urls:
    page = requests.get(dire).text
    finca_raiz = BeautifulSoup(page,'html.parser')
    direc = ''
    barrio = ''
    municipio = ''
    valor = ''
    parqueaderos = ''
    habitaciones = ''
    banos = ''
    area_construida = ''
    area_privada = ''
    estrato = ''
    tipo = ''
    latitud = ''
    longitud = ''
    estado = ''
    antiguedad =''
    piso = ''
    administracion = ''
    precio_m2 = ''
    
    if re.findall(r'address":"[\w+\s#-\.]*',page)!=[]:
        direccion = re.findall(r'address":"[\w+\s#-\.]*',page)
        direc = direccion[0][direccion[0].find(":")+2:len(direccion[0])].strip()
    
    if finca_raiz.find('p',attrs={'class':'jss64 jss72 jss141'}) is not None:
        barrio_municipio = finca_raiz.find('p',attrs={'class':'jss64 jss72 jss141'}).text
        barrio = barrio_municipio[0:barrio_municipio.find('-')-1]
        municipio = barrio_municipio[barrio_municipio.find('-')+2:len(barrio_municipio)]
        
    
    if re.findall(r'Precio total \(COP\)</p><p\s?class\="[\w+\s]+">',page)!=[]:
        atributo_precio = str(re.findall(r'Precio total \(COP\)</p><p\s?class\="[\w+\s]+">',page))
        atributo_precio=atributo_precio[atributo_precio.find('"')+1:atributo_precio.rfind('"')]
        valor = finca_raiz.find('p',attrs={'class':atributo_precio}).text
    
    
    if re.findall(r'Desde \(COP\)</p><p\s?class\="[\w+\s]+">',page)!=[]:
        atributo_precio = str(re.findall(r'Desde \(COP\)</p><p\s?class\="[\w+\s]+">',page)[0])
        atributo_precio=atributo_precio[atributo_precio.find('"')+1:atributo_precio.rfind('"')]
        valor = finca_raiz.find('p',attrs={'class':atributo_precio}).text
    
    
    if finca_raiz.find('p',attrs={'class':'jss64 jss69 jss123'}) is not None:
        tipo = finca_raiz.find('p',attrs={'class':'jss64 jss69 jss123'}).text
    
    if re.findall(r'Habitaciones:\s\d{1,}',page)!=[]:
        habitaciones = re.findall(r'\d{1,}',str(re.findall(r'Habitaciones:\s\d{1,}',page)))[0]
    
    if re.findall(r'Baños:\s\d{1,}',page)!=[]:
        banos = re.findall(r'\d{1}',str(re.findall(r'Baños:\s\d{1,}',page)))[0]
    
    if re.findall(r'Parqueaderos</p><p\s?class\="[\w+\s]+">\d{1,}',page)!=[]:
        if re.findall(r'>\d{1,}',str(re.findall(r'Parqueaderos</p><p\s?class\="[\w+\s]+">\d{1,}',page)))!=[]:
            parqueaderos_texto = re.findall(r'>\d{1,}',str(re.findall(r'Parqueaderos</p><p\s?class\="[\w+\s]+">\d{1,}',page)))
            parqueaderos = re.findall(r'\d{1,}',str(parqueaderos_texto))[0]
    
    if re.findall(r'Área construída</p><p\s?class\="[\w+\s]+">\d{1,}\s?m',page)!=[]:
        if re.findall(r'>\d{1,}',str(re.findall(r'Área construída</p><p\s?class\="[\w+\s]+">\d{1,}\s?m',page)))!=[]:
            area_construida_texto = re.findall(r'>\d{1,}',str(re.findall(r'Área construída</p><p\s?class\="[\w+\s]+">\d{1,}',page)))
            area_construida = re.findall(r'\d{1,}',str(area_construida_texto))[0]
            
    
    if re.findall(r'Área privada</p><p\s?class\="[\w+\s]+">\d{1,}\s?m',page)!=[]:
        if re.findall(r'>\d{1,}',str(re.findall(r'Área privada</p><p\s?class\="[\w+\s]+">\d{1,}\s?m',page)))!=[]:
            area_privada_texto = re.findall(r'>\d{1,}',str(re.findall(r'Área privada</p><p\s?class\="[\w+\s]+">\d{1,}',page)))
            area_privada = re.findall(r'\d{1,}',str(area_privada_texto))[0]
          
    
    if re.findall(r'Estrato</p><p\s?class\="[\w+\s]+">\d{1,}',page)!=[]:
        if re.findall(r'>\d{1,}',str(re.findall(r'Estrato</p><p\s?class\="[\w+\s]+">\d{1,}',page)))!=[]:
            estrato_texto = re.findall(r'>\d{1,}',str(re.findall(r'Estrato</p><p\s?class\="[\w+\s]+">\d{1,}',page)))
            estrato = re.findall(r'\d{1,}',str(estrato_texto))[0]
         
   
    if re.findall(r'Estado</p><p\s?class\="[\w+\s]+">\w+',page)!=[]:
        if re.findall(r'>\w+',str(re.findall(r'Estado</p><p\s?class\="[\w+\s]+">\w+',page)))!=[]:
            estado_texto = re.findall(r'>\w+',str(re.findall(r'Estado</p><p\s?class\="[\w+\s]+">\w+',page)))
            estado = re.findall(r'\w+',str(estado_texto))[0]
         
    
    if re.findall(r'Antiguedad:\s*\w+\s*\w+\s*\d{0,}\s*\w+',page)!=[]:
        antiguedad_texto = str(re.findall(r'Antiguedad:\s*\w+\s*\w+\s*\d{0,}\s*\w+',page)[0])
        antiguedad = antiguedad_texto[antiguedad_texto.find(' ')+1:len(antiguedad_texto)]
        
    
    if re.findall(r'Piso N°</p><p\s?class\="[\w+\s]+">\w+',page)!=[]:
        if re.findall(r'>\w+',str(re.findall(r'Piso N°</p><p\s?class\="[\w+\s]+">\w+',page)))!=[]:
            piso_texto = re.findall(r'>\w+',str(re.findall(r'Piso N°</p><p\s?class\="[\w+\s]+">\w+',page)))
            piso = re.findall(r'\w+',str(piso_texto))[0]

    if re.findall(r'Administración</p><p\s?class\="[\w+\s]+">',page)!=[]:
        atributo = str(re.findall(r'Administración</p><p\s?class\="[\w+\s]+">',page))
        atributo=atributo[atributo.find('"')+1:atributo.rfind('"')]
        administracion = finca_raiz.find('p',attrs={'class':atributo}).text
   
    
    if re.findall(r'Precio m²</p><p\s?class\="[\w+\s]+">',page)!=[]:
        atributo = str(re.findall(r'Precio m²</p><p\s?class\="[\w+\s]+">',page))
        atributo=atributo[atributo.find('"')+1:atributo.rfind('"')]
        precio_m2 = finca_raiz.find('p',attrs={'class':atributo}).text
    
    
    #Latitud longitud     
    latitud_longitud = ''
    
    if re.findall(r'lat"\:\d{1,}\.?\d{1,}',page)!=[]:
        latitud = re.findall(r'lat"\:\d{1,}\.?\d{1,}',page)[0]
        latitud = re.findall(r'\d{1,}\.?\d{1,}',latitud)[0]
        
    if re.findall(r'lng"\:-\d{1,}\.?\d{1,}',page)!=[]:
        longitud = re.findall(r'lng"\:-\d{1,}\.?\d{1,}',page)[0]
        longitud = re.findall(r'-\d{1,}\.?\d{1,}',longitud)[0]
        
    if re.findall(r'center=\d{1,}\.?\d{1,}\,-\d{1,}\.?\d{1,}',page)!=[]:
        latitud_longitud = str(re.findall(r'center=\d{1,}\.?\d{1,}\,-\d{1,}\.?\d{1,}',page))
    
    if re.findall(r'center=\d{1,}\.?\d{1,}\,-\d{1,}\.?\d{1,}',page)!=[]:
        latitud_longitud = str(re.findall(r'center=\d{1,}\.?\d{1,}\,-\d{1,}\.?\d{1,}',page))
    
    if re.findall(r'\-?\d{1,}\.\d{1,}',latitud_longitud) !=[]:
        latitud = re.findall(r'\-?\d{1,}\.\d{1,}',latitud_longitud)[0]
        longitud = re.findall(r'\-?\d{1,}\.\d{1,}',latitud_longitud)[1]
    
    folio='Finca_'+re.findall(r'\d{2,}',dire)[0]
    
    data.append((ano, mes, dia, direc, barrio, municipio, valor, tipo, habitaciones, banos, parqueaderos,area_construida, area_privada,
                 estrato, estado, antiguedad, piso, administracion, precio_m2, folio, latitud, longitud, dire))
    registros +=1
    print(registros)
df=pd.DataFrame(data,columns=['Año', 'Mes', 'Día', 'direccion', 'barrio', 'municipio', 'Valor', 'Tipo', 'habitaciones', 'banos', 'parqueadero', 'Area Construida','Área Privada', 
                              'estrato','Estado','antiguedad','Piso','Administracion', 'Precio_m2', 'Folio', 'Latitud','Longitud','Url'])
df.to_excel(r'/content/Finca'+fecha+'.xlsx',header=True,index=False)